### ISSUE TITLE
[BUG] Size of patched image is larger than target device

### ISSUE THREAD

**Issue by kaneawk** [erfanoabdi/imgpatchtools#1]
## Environment
Verison of imgpathtools: this commit : a9d73a52d3a90376888e1fc1a5b2d5fb90cfa6f6
OS version: Ubuntu 16.04

## What did you find?
Patched system.img size: 5,704,257,536B == 5570564KB
System actual partition size: 5570560KB

## BUG Description
Patched system image larger than target device. Unfortunately, Not just system, oem partition also occurred this problem.

## What advice do you have?
No, I have not found the cause of the problem. 😢

**Comment by erfanoabdi** [comment]
are you sure image size changed after patching?

**Comment by kaneawk** [comment]
Sorry for the delay. 

I can use the imgpatchtools patch image normally, imgpathtools works well. image size has not changed after patching.

It looks like simg2img's or fastboot problem?

On my motoz, I use simg2img convert system.img_sparsechunk* to system.img, then remove the moto image signature, let it become a standard ext4 image. but I  can't use mfastboot/fastboot to flash it, the fastboot will show an error on the last sparse, although i did not use imgpatchtools. 

On my moto x force, I can use fastboot flash the converted ext4 image directly.

The system partition size is smaller than the converted ext4 image.

`adb shell su -c cat /proc/partitions`

1|griffin:/ # cat /proc/partitions
major minor  #blocks  name

   7        0      65536 loop0
 254        0     524288 zram0
   8        0   62181376 sda
   8        1        512 sda1
   8        2        512 sda2
   8        3      32768 sda3
   8        4        128 sda4
   8        5       1024 sda5
   8        6          8 sda6
   8        7        512 sda7
   8        8      32768 sda8
   8        9      16384 sda9
   8       10       8192 sda10
   8       11       4608 sda11
   8       12       2048 sda12
   8       13       2048 sda13
   8       14      32772 sda14
   8       15    5570560 sda15
……

5570560*1024=5704253440

`ls system.img.raw`

`Mode                LastWriteTime         Length Name`
`----                -------------         ------ ----`
`-a----         2017/8/5      1:25     5704257536 system.img.raw`

**Comment by erfanoabdi** [comment]
no problem ;)
when i take closer look with hex editor i found out there's also moto footer for moto z images

<img width="395" alt="motofooter" src="https://user-images.githubusercontent.com/7512922/28998037-4161707a-7a37-11e7-9021-a775cd554730.png">

you can use head command to remove it : 
`head -c $(( 4*1024*-1 )) system.img >system2.img`

**Comment by kaneawk** [comment]
Thank you!
