### ISSUE TITLE
Infinite loop while patching Samsung Galaxy S21 Ultra 5G Exynos Oneui 3 to 4 beta using their ota zip.

### ISSUE THREAD

**Issue by VDavid003** [erfanoabdi/imgpatchtools#11]
Using the Samsung Galaxy S21 Ultra 5g Oneui4 update.zip from [this XDA thread](https://forum.xda-developers.com/t/oneui-4-0-beta-1-exynos-update-zip-for-s21-plus-ultra-download-ota-link.4333487/) to patch system.img, the program results in an infinite loop. It is caused by the following move in the transfer.list:
```move f48e359a0543280719069120db061ee3d3040c21 2,1613403,1613596 193 2,1528948,1529141```
Using printfs to debug, it seems like in the read_all function, ota_read (and read itself) returns 0, so 0 gets added to so_far, and it reads again in an infinite loop. It also seems like in LoadSrcTgtVersion3, it calls LoadSrcTgtVersion2 in which ReadBlocks gets called which calls read_all and succeeds, but then  LoadSrcTgtVersion3 itself calls ReadBlocks and it actually freezes.

**Comment by VDavid003** [comment]
I got past the issue by removing the code that checks if the move has already been done but this should be fixed somehow

**Comment by afaneh92** [comment]
> 

can you share what you did for the code

**Comment by VDavid003** [comment]
> > 
> 
> can you share what you did for the code

If I remember correctly, removing lines 1051-1054 from https://github.com/erfanoabdi/imgpatchtools/blob/30dcd07bd80cd4dacd0c24c3a17559462d5e0e95/blockimg/blockimg.cpp#L1051-L1054 fixed the issue for me, but I will need to check to be sure. Do keep in mind though, that this will make the program not skip patches that are already applied making the image probably corrupt if you rerun the patch.

**Comment by erfanoabdi** [comment]
fixed, thanks @VDavid003
