### ISSUE TITLE
patching boot.img

### ISSUE THREAD

**Issue by JonnyTech** [erfanoabdi/imgpatchtools#4]
My OTA contains a `/patch/boot.img.p` file which is mentioned in the update script:

```
$ cat META-INF/com/google/android/updater-script |grep -i -B 3 -A 2 boot.img.p
apply_patch("EMMC:/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/boot:9089280:6bfdeb6cfea452d44791cab2b5d3038d43c4e948:8917248:b1400bf1209617fb398d821ed6c17015e606c134",
            "-", b1400bf1209617fb398d821ed6c17015e606c134, 8917248,
            6bfdeb6cfea452d44791cab2b5d3038d43c4e948,
            package_extract_file("patch/boot.img.p")) ||
    abort("E3008: Failed to apply patch to EMMC:/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/boot:9089280:6bfdeb6cfea452d44791cab2b5d3038d43c4e948:8917248:b1400bf1209617fb398d821ed6c17015e606c134");
ui_print("Writing radio image...");
```

File details for existing and OTA files: 

```
$ file boot.img 
boot.img: Android bootimg, kernel (0x40080000), ramdisk (0x44000000), page size: 2048, cmdline (bootopt=64S3,32N2,64N2)
$ file boot.img.p 
boot.img.p: data
```

Can the file be patched easily?

**Comment by erfanoabdi** [comment]
yes it's easier then system image
just use this : 
`./ApplyPatch boot.img - b1400bf1209617fb398d821ed6c17015e606c134 8917248 6bfdeb6cfea452d44791cab2b5d3038d43c4e948 patch/boot.img.p`

**Comment by JonnyTech** [comment]
Genius. Thank you.

```
$ ./ApplyPatch boot.img - b1400bf1209617fb398d821ed6c17015e606c134 8917248 6bfdeb6cfea452d44791cab2b5d3038d43c4e948 new/boot.img.p
creating cache dir cache
cache dir: cache
patch boot.img: 
now b1400bf1
Done with error code : 0
$ file boot.img 
boot.img: Android bootimg, kernel (0x40080000), ramdisk (0x44000000), page size: 2048, cmdline (bootopt=64S3,32N2,64N2)
```

**Comment by psychopathologist** [comment]
@erfanoabdi 
Is there any way for ApplyPatch to work on this android 12 ota updater-script?

```
patch_partition(concat("EMMC:","/dev/block/by-name/boot",":61865984:c724f99a0ed3ba07a2019afee99a51f819390d06"),
                concat("EMMC:","/dev/block/by-name/boot",":61865984:db8f919bcdbd52c010f22e44a7a7b66fb03aba20"),
                package_extract_file("boot.img.p")) ||
    abort(concat(        "E3008: Failed to apply patch to ",concat("EMMC:","/dev/block/by-name/boot",":61865984:db8f919bcdbd52c010f22e44a7a7b66fb03aba20")));
```

Tia!

**Comment by sircode** [comment]
> b1400bf1209617fb398d821ed6c17015e606c134 8917248 6bfdeb6cfea452d44791cab2b5d3038d43c4e948

Noob asking:  where do I get this from? I have boot.img (from Stock Rom) and boot.img.p (from OTA update 2.2), and need the final patched boot.img

**Comment by chouex** [comment]
> @erfanoabdi Is there any way for ApplyPatch to work on this android 12 ota updater-script?
> 
> ```
> patch_partition(concat("EMMC:","/dev/block/by-name/boot",":61865984:c724f99a0ed3ba07a2019afee99a51f819390d06"),
>                 concat("EMMC:","/dev/block/by-name/boot",":61865984:db8f919bcdbd52c010f22e44a7a7b66fb03aba20"),
>                 package_extract_file("boot.img.p")) ||
>     abort(concat(        "E3008: Failed to apply patch to ",concat("EMMC:","/dev/block/by-name/boot",":61865984:db8f919bcdbd52c010f22e44a7a7b66fb03aba20")));
> ```
> 
> Tia!

How to apply boot.img.p to old boot.img:
prepear an rooted phone,
WARNING: you will modify boot partition during patch, backup boot before patch and restore boot(or previous version boot.img if you update os) after patch.
1. cp /dev/block/by-name/boot /sdcard/Download/boot-now-using.img # backup 
2. extract boot.img.p from update zip into `/sdcard/Download/boot.img.p`
4. restore previous boot.img to /dev/block/by-name/boot (yes you have to find the original version boot.img having sha1 of db8f919bcdbd52c010f22e44a7a7b66fb03aba20 in your case)
5. find hash in updatezip: META-INF\com\google\android\updater-script search for boot.img.p
6. adb shell applypatch --patch /sdcard/Download/boot.img.p --source EMMC:/dev/block/by-name/boot:61865984:db8f919bcdbd52c010f22e44a7a7b66fb03aba20 --target EMMC:/dev/block/by-name/boot:61865984:c724f99a0ed3ba07a2019afee99a51f819390d06
7. now you have new boot.img at /dev/block/by-name/boot
8. sha1sum /dev/block/by-name/boot # c724f99a0ed3ba07a2019afee99a51f819390d06
9. cp /dev/block/by-name/boot /sdcard/Download/boot-new.img
10. you should recover old original boot.img before apply update to os.
11. you may need new version of boot.img for next update, dont forget backup (not the magisk-patched one).

**Comment by cash83** [comment]
hi, who can help me install the program on ubuntu? I'm a beginner. I have to patch the boot.img.p file of an Android Wear OS 3.5. the program does not start. Thank you

**Comment by KawaiiSparkle** [comment]
![PixPin_2024-06-25_12-24-00](https://github.com/erfanoabdi/imgpatchtools/assets/156587835/9060c9cc-b91d-4ef4-9db1-0b5dff7e3198)
You only need to know the After_patching_size After_patching_sha1 and Before_patching_sha1,and input them like this below:
```
Applypatch boot.img - <After_patching_sha1> <After_patching_size> <Before_patching_sha1> boot.img.p
```

**Comment by cash83** [comment]
> ![PixPin_2024-06-25_12-24-00](https://private-user-images.githubusercontent.com/156587835/342580640-9060c9cc-b91d-4ef4-9db1-0b5dff7e3198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM3OTMsIm5iZiI6MTcxOTM5MzQ5MywicGF0aCI6Ii8xNTY1ODc4MzUvMzQyNTgwNjQwLTkwNjBjOWNjLWI5MWQtNGVmNC05ZGIxLTBiNWRmZjdlMzE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwOTE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjQ1ZjljYzg3MTBlNjlmM2MyYmRhM2NjMGNiYTg2MGU4OTZhZmQzNGFlZDA5YzU2YTRkYWVmNjM3NDE2YzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jTidLrlVJhJriRYn-dhJTyFqiT_KBz_G8xgnHU2330I) Devi solo conoscere After_patching_size After_patching_sha1 e Before_patching_sha1 e inserirli in questo modo di seguito:
> 
> ```
> Applypatch boot.img - <After_patching_sha1> <After_patching_size> <Before_patching_sha1> boot.img.p
> ```

hi thanks for the reply... if I give you the boot.bin file could you do it?  I'm not really capable.  I tried many times but I couldn't.  Thank you
[boot.zip](https://github.com/user-attachments/files/15985589/boot.zip)

**Comment by JonnyTech** [comment]
@cash83 please also supply the `boot.img.p` file from the OTA .zip

```
$ ./ApplyPatch boot.bin boot.bin.patched 0dd37e45a320c15d89a2c9affd43dc8c2b344a38 4802048 90c339e102edebb587d8d317a1b4108ff690ef94
usage: ./ApplyPatch <file> <target> <tgt_sha1> <size> <init_sha1(1)> <patch(1)> [init_sha1(2)] [patch(2)] ...

	<file> = source file from rom zip
	<target> = target file (use "-" to patch source file)
	<tgt_sha1> = target SHA1 Sum after patching
	<size> = file size
	<init_sha1> = file SHA1 sum
	<patch> = patch file (.p) from OTA zip
```

**Comment by cash83** [comment]
> @cash83si prega di fornire anche il `boot.img.p`file dall'OTA .zip
> 
> ```
> $ ./ApplyPatch boot.bin boot.bin.patched 0dd37e45a320c15d89a2c9affd43dc8c2b344a38 4802048 90c339e102edebb587d8d317a1b4108ff690ef94
> usage: ./ApplyPatch <file> <target> <tgt_sha1> <size> <init_sha1(1)> <patch(1)> [init_sha1(2)] [patch(2)] ...
> 
> 	<file> = source file from rom zip
> 	<target> = target file (use "-" to patch source file)
> 	<tgt_sha1> = target SHA1 Sum after patching
> 	<size> = file size
> 	<init_sha1> = file SHA1 sum
> 	<patch> = patch file (.p) from OTA zip
> ```

@JonnyTech  thank you very much for the help in the uncle there is the boot.bin file and the boot.img.p file 
[ROVER_WEAR3.5.zip](https://github.com/user-attachments/files/16012749/ROVER_WEAR3.5.zip)
Ota update meta-inf
[META-INF.zip](https://github.com/user-attachments/files/16014492/META-INF.zip)

**Comment by KawaiiSparkle** [comment]
@cash83 
You should input this below
```
./Applypatch boot.bin - 47d18c8ed78b322dec4655f0dec37b5874d81742 33554432 d2a7f218f8a6e9fc4ed277a78843afbb2a68d9d2 boot.img.p
```
It's just a simply imitate.

**Comment by cash83** [comment]
> @cash83 Dovresti inserirlo qui sotto
> 
> ```
> ./Applypatch boot.bin - 47d18c8ed78b322dec4655f0dec37b5874d81742 33554432 d2a7f218f8a6e9fc4ed277a78843afbb2a68d9d2 boot.img.p
> ```
> 
> È semplicemente un'imitazione.

thanks for the answer... I tried with Windows but it doesn't do anything... I also tried with Ubuntu but it gives me errors that I can't remember now.
I'm sure I'll do something stupid wrong but I've tried many, many times.  my problem is having an lte ticwach if I don't change the APN I can't change it and I can't access the internet.  so I need it to be able to root via magisk.

**Comment by JonnyTech** [comment]
```
$ ./ApplyPatch boot.bin boot.new 47d18c8ed78b322dec4655f0dec37b5874d81742 33554432 d2a7f218f8a6e9fc4ed277a78843afbb2a68d9d2 boot.img.p 
creating cache dir cache
cache dir: cache
patch boot.bin: 
patch did not produce expected sha1
Done with error code : 1
```

Are you sure that the `boot.img` and `boot.img.p` are both for the same device? Can you provide direct download links?

**Comment by cash83** [comment]
> ```
> $ ./ApplyPatch boot.bin boot.new 47d18c8ed78b322dec4655f0dec37b5874d81742 33554432 d2a7f218f8a6e9fc4ed277a78843afbb2a68d9d2 boot.img.p 
> creating cache dir cache
> cache dir: cache
> patch boot.bin: 
> patch did not produce expected sha1
> Done with error code : 1
> ```
> 
> Sei sicuro che `boot.img`e `boot.img.p`siano entrambi per lo stesso dispositivo? Potete fornire i link per il download diretto?

yes I'm sure... the files are on telegram.  update file I downloaded it from my update.  instead the other was extracted from the system dump (I don't know if I can post the link here... )anyway I extracted the boot.bin file in boot.img could that be the error?
[boot.zip](https://github.com/user-attachments/files/16019332/boot.zip)

**Comment by JonnyTech** [comment]
You can try the patched file: [boot.zip](https://github.com/user-attachments/files/16019642/boot.zip) in case the error (`patch did not produce expected sha1`) is bogus.

**Comment by cash83** [comment]
> Puoi provare il file patchato: [boot.zip](https://github.com/user-attachments/files/16019642/boot.zip) nel caso in cui l'errore ( `patch did not produce expected sha1`) sia fasullo.

Ok I'll try tomorrow now I'm at work and I'll dismantle tomorrow morning... thanks for your great help

**Comment by cash83** [comment]
> Puoi provare il file patchato: [boot.zip](https://github.com/user-attachments/files/16019642/boot.zip) nel caso in cui l'errore ( `patch did not produce expected sha1`) sia falso.

thanks for your support but the file doesn't work.  the flash is successful but the smartwatch restarts in the bootloader
